// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command 192.168.1.72:4200 set NODE_OPTIONS=--max_old_space_size=4096
import env from './.env';

export const UrlConfig: any = {
  serverApi:        'https://apis.sangnn.vn:8282',
  clientAddress: 'http://10.30.132.79:8350',
  ssoAddress: 'https://10.30.132.79:8225/sso',
};
export const environment: any = {
  production: true,
  version: env.npm_package_version + '-dev',
  serverUrl: {
    // political   : UrlConfig.serverApi + '/political-service',
    political   : 'http://10.30.132.79:8081',
    oauth       : 'http://10.30.132.21:8902',
    file        : 'http://10.30.132.79:8389',
    // report      : UrlConfig.serverApi + "/political-report",=
    report      : 'http://10.30.132.79:8082',
    //assessment  : UrlConfig.serverApi + "/assess-political-service",
    assessment  : 'http://10.30.132.79:8084',
  }
};
/** custom Constants variable */
export const Constants = {
  applicationCode: 'CTCT',
  nationId: 'nationId',
  nationConfig: 'nation_config'
};

/** Config default variable */
export const ConfigDefault = {
  dateFormat: 'dd/MM/yyyy'
};
/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
