import { Routes } from '@angular/router';

export const CONTENT_ROUTES: Routes = [
  {
    path: 'home-page',
    loadChildren: './modules/home-page/home-page.module#HomePageModule'
  }, {
    path: 'employee',
    loadChildren: './modules/employee/employee.module#EmployeeModule'
  }, {
    path: 'document',
    loadChildren: './modules/document/document.module#DocumentModule'
  }, {
    path: 'notification',
    loadChildren: './modules/notification/notification.module#NotificationModule'
  }, {
    path: 'settings',
    loadChildren: './modules/settings/settings.module#SettingsModule'
  }, {
    path: 'party-organization',
    loadChildren: './modules/party/party.module#PartyModule'
  }, {
    path: 'organization-tree',
    loadChildren: './modules/organization-chart/organization-chart.module#OrganizationChartModule'
  }, {
    path: 'mass',
    loadChildren: './modules/mass-organization/mass-organization.module#MassOrganizationModule'
  }, {
    path: 'organization-tree',
    loadChildren: './modules/organization-chart/organization-chart.module#OrganizationChartModule'
  }, {
    path: 'sign-manager',
    loadChildren: './modules/sign-manager/sign.module#SignModule'
  }, {
    path: 'population',
    loadChildren: './modules/population/population.module#PopulationModule'
  }, {
    path: 'security-guard',
    loadChildren: './modules/security/security.module#SecurityModule'
  }, {
    path: 'propaganda',
    loadChildren: './modules/propaganda/propaganda.module#PropagandaModule'
  }, {
    path: 'send-notification',
    loadChildren: './modules/send-notification/send-notification.module#SendNotificationModule'
  }, {
    path: 'policy-program',
    loadChildren: './modules/policy-program/policy-program.module#PolicyProgramModule'
  }, {
    path: 'monitoring-inspection',
    loadChildren: './modules/monitoring/monitoring.module#MonitoringModule'
  }, {
    path: 'reports',
    loadChildren: './modules/reports/reports.module#ReportsModule'
  }, {
    path: 'voffice-signing',
    loadChildren: './modules/voffice-signing/voffice-signing.module#VofficeSigningModule'
  }, {
    path: 'report',
    loadChildren: './modules/report/report.module#ReportModule'
  }, {
    path: 'admin',
    loadChildren: './modules/admin/admin.module#AdminModule'
    
  }, {
    path: 'reward',
    loadChildren: './modules/reward/reward.module#RewardModule'
  }, {
    path: 'fund',
    loadChildren: './modules/fund/fund.module#FundModule'
  }, {
    path: 'mass-group',
    loadChildren: './modules/mass-group/mass-group.module#MassGroupModule'
  }, {
    path: 'allowance',
    loadChildren: './modules/allowance/allowance.module#AllowanceModule'
  }, {
    path: 'subsidized',
    loadChildren: './modules/subsidized/subsidized.module#SubsidizedModule'
  }, {
    path: 'competition-unit-registration',
    loadChildren: './modules/competition-unit-registration/competition-unit-registration.module#UnitRegistrationModule'
  }, {
    path: 'competition-program',
    loadChildren: './modules/competition-program/competition-program.module#CompetitionProgramModule'
  }, {
    path: 'commit-to-comply-tet',
    loadChildren: './modules/commit-to-comply-tet/commit-to-comply-tet.module#CommitToComplyTetModule'
  }
];
